# Generated by Django 5.1.5 on 2025-02-11 11:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUsers',
            fields=[
                ('username', models.CharField(default='default_username', max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(default='default_name', max_length=16)),
                ('tracks_count', models.IntegerField(default=0)),
                ('favorite_artist', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_date', models.DateTimeField(default=datetime.datetime(2025, 2, 11, 11, 29, 54, 155088, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='UsersTracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.IntegerField(unique=True)),
                ('artist', models.CharField(max_length=255)),
                ('track_title', models.CharField(max_length=255)),
                ('cover_url', models.URLField(blank=True, max_length=500, null=True)),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.appusers')),
            ],
        ),
    ]
