# Generated by Django 5.1.5 on 2025-02-11 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_appusers_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appusers',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 11, 11, 34, 24, 84935, tzinfo=datetime.timezone.utc)),
        ),
    ]
