# Generated by Django 5.1.5 on 2025-02-11 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userstracks_artist_userstracks_cover_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appusers',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 11, 11, 53, 48, 138491, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userstracks',
            name='track_id',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
