# Generated by Django 5.1.5 on 2025-02-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userstracks_added_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appusers',
            name='password',
            field=models.CharField(default='default_pass', max_length=16),
        ),
    ]
