# Generated by Django 5.1.5 on 2025-02-12 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_appusers_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appusers',
            name='password',
            field=models.CharField(default='default_pass', max_length=32),
        ),
    ]
