# Generated by Django 5.1.5 on 2025-02-12 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_appusers_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appusers',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='appusers',
            name='username',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
    ]
