# Generated by Django 5.1.5 on 2025-02-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_appusers_password_alter_appusers_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appusers',
            name='password',
        ),
        migrations.AlterField(
            model_name='appusers',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='appusers',
            name='username',
            field=models.CharField(max_length=16, primary_key=True, serialize=False, unique=True),
        ),
    ]
